
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wahanaad/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R plugins $DEPLOYPATH
    - /bin/cp -R ridwan.wahana $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    
